### ISSUE TITLE
Using Air 3.3 & 3.4 SDK causing errors

### ISSUE THREAD

**Issue by sbleicker** [wouterverweirder/AIR-Mobile-UDP-Extension#8]
Hi Wouter,

I need the updated SDK 4.6.0 files (with Air 3.3) update to get retina support (higher text quality) and because of a LocalNotification ANE, which seems only run with the AIR 3.3 SDK.

With this sdk, I'm getting errors creating a build:

Fehler beim Verpacken der Anwendung:

Undefined symbols for architecture armv7:
  "_UDPSocketiOSLibraryExtInitializer", referenced from:
      _g_com_adobe_air_fre_fmap in extensionglue.o
     (maybe you meant: _UDPSocketiOSLibraryExtInitializer_name)
  "_UDPSocketiOSLibraryExtFinalizer", referenced from:
      _g_com_adobe_air_fre_fmap in extensionglue.o
     (maybe you meant: _UDPSocketiOSLibraryExtFinalizer_name)
ld: symbol(s) not found for architecture armv7
Compilation failed while executing : ld64

Any idea what to do?

Regards

Stefan

**Comment by sbleicker** [comment]
Hi,

I tried to compile with AIR3.4 SDK - not running. 
Here is the Error:
Fehler beim Verpacken der Anwendung:

ld: warning: -ios_version_min not specificed, assuming 4.0
ld: warning: ignoring file /var/folders/33/q1hx62cs7yj0_sb3_c1smqhc0000gn/T/34e3e663-05e5-4efd-b9e3-921a33f3d8d1/libbe.aboutme.nativeExtensions.udp.UDPSocket.a, file was built for archive which is not the architecture being linked (armv7)
Undefined symbols for architecture armv7:
  "_UDPSocketiOSLibraryExtInitializer", referenced from:
      _g_com_adobe_air_fre_fmap in extensionglue.o
     (maybe you meant: _UDPSocketiOSLibraryExtInitializer_name)
  "_UDPSocketiOSLibraryExtFinalizer", referenced from:
      _g_com_adobe_air_fre_fmap in extensionglue.o
     (maybe you meant: _UDPSocketiOSLibraryExtFinalizer_name)
ld: symbol(s) not found for architecture armv7
Compilation failed while executing : ld64

Regards

Stefan

**Comment by wouterverweirder** [comment]
Seems to be AIR 3.3 issue indeed, works perfectly on 3.1. Will look into this...

**Comment by sbleicker** [comment]
Great!
Thx

**Comment by wouterverweirder** [comment]
I've updated the ANE to work with latest version of AIR (3.4). It fixes the error here.

**Comment by sbleicker** [comment]
Hi Wouter,

in 3.3 it works perfectly!

But in 3.4 I receive a runtime error:
Error: Error #3502: The extension returned an invalid value.
    at flash.external::ExtensionContext/_call()
    at flash.external::ExtensionContext/call()
    at be.aboutme.nativeExtensions.udp::UDPSocket/statusHandler()[/Users/wouter/Documents/experiments/AIR-Mobile-UDP-Extension/as3 code/UDPSocket/src/be/aboutme/nativeExtensions/udp/UDPSocket.as:86]

Maybe, I made a mistake merging the Air 3.4 SDK into the Flex SDK if it works on your Flex installation.

Regards

Stefan

**Comment by wouterverweirder** [comment]
That's odd. I've used Flex SDK 4.6 with AIR 3.4, overlayed AIR following the instructions on http://helpx.adobe.com/x-productkb/multi/how-overlay-air-sdk-flex-sdk.html

**Comment by sbleicker** [comment]
Hi Wouter,

it's crazy, after a new merge of SDK 4.6 it works. Now, without changing the skd there is the same error as before:

Error: Error #3502: The extension returned an invalid value.
    at flash.external::ExtensionContext/_call()
    at flash.external::ExtensionContext/call()
    at be.aboutme.nativeExtensions.udp::UDPSocket/statusHandler()[/Users/wouter/Documents/experiments/AIR-Mobile-UDP-Extension/as3 code/UDPSocket/src/be/aboutme/nativeExtensions/udp/UDPSocket.as:86]

I didn't know whats going wrong - maybe you can have a look at the UDPSocket.as:86? 

Regards

Stefan

**Comment by sbleicker** [comment]
Hi Wouter,

I made a complete new Overlay, now with instructions from http://www.jasonsturges.com/2012/08/overlay-adobe-air-3-4-sdk-in-flash-builder-4-6/
There are discribed some additional changes in the SDK.

Buth without success, still the same error.

I'm not sure if it ever runs in 3.4. I made an SDK Update to 3.4 cause of iOS6. But I can not exactly say that I checked the UDP Extension in 3.4, maybe only in 3.3

I will now uninstall my complete Flash Builder framework and try a fresh install...

Regards

Stefan

**Comment by sbleicker** [comment]
Clean Install -> Same problem.

UDPSocket sends request, receive answer! and then Error.

**Comment by sbleicker** [comment]
Hi,

seems that an web-service request (which gets an 404) that is made parallel to the udp requests triggers the error.
So, fixing teh ws-request solves the problem - stupid...

Regards
Stefan

**Comment by wouterverweirder** [comment]
weird! Thanks for looking into that, didn't have to do anything ;-)

**Comment by sbleicker** [comment]
Hi Wouter,
post was written too early...
Problem still exists, but only in debug mode. If I make a non-debug release, the function completes (its not crashing and returns every info I need).

Regards
Stefan
